# -*- coding: utf-8 -*-
"""Análise Séries Temporais _Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEXNuqH658wFx9WvmoDwxi_Y5qVOR3m8

# ANÁLISE DE DADOS E SÉRIES TEMPORAIS COM PYTHON ♦
"""

# ==============================================================================
# PROJETO ENERGY&ETL: Predição de Potência Elétrica baseada na Corrente
# ==============================================================================

# 1. Importando as bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Carregamento do arquivo bruto e sepração das colunas

# Read the excel file, assuming it has one column where data is comma-separated
df_bruto = pd.read_excel('/content/Base_de_Dados_Eletrica (1).xlsx')

# Tratando a estrutura do arquivo (separando a coluna única em 4 colunas)
nome_coluna_unica = df_bruto.columns[0] # Pega o nome da coluna aglutinada
df = df_bruto[nome_coluna_unica].str.split(',', expand=True)
df.columns = ['data', 'tensao_V', 'corrente_A', 'potencia_W']

# Convertendo os tipos de dados
df['data'] = pd.to_datetime(df['data'])
df['tensao_V'] = pd.to_numeric(df['tensao_V'])
df['corrente_A'] = pd.to_numeric(df['corrente_A'])
df['potencia_W'] = pd.to_numeric(df['potencia_W'])


print(df.head(), '\n')

df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
linhas_vazias = df[df.isnull().any(axis=1)]

if linhas_vazias.empty:
  print("Não há linhas com valores nulos.")
else:
  print(f"Linhas e colunas com valores nulos:\n{df.isnull().sum()}")

# Removendo valores nulos para evitar erros nos cálculos e modelos
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df = df.dropna().copy()
print(df.head())

print()

# Filtra o DataFrame para mostrar apenas as linhas que têm pelo menos um valor nulo
linhas_vazias = df[df.isnull().any(axis=1)]

# Mostra a quantidade de linhas e colunas no formato (linhas, colunas)
print("A quantidade de linhas e colunas são: ", df.shape )

# Exibe o resultado na tela
if linhas_vazias.empty:
  print("Não há linhas e colunas com valores nulos e vazios. ")
else:
  print("Linhas e/ou colunas com valores nulos:")

# Normalização e padronização dos dados

# Configurando a data como índice para facilitar a análise temporal
df = df.reset_index()    # Ensure 'data' is a column before setting as index
df.set_index('data', inplace=True)

# 3. Normalização e Padronização nas variáveis contínuas
variaveis = ['tensao_V', 'corrente_A', 'potencia_W']

# Normalização (Min-Max: escala de 0 a 1)
scaler_minmax = MinMaxScaler()
df_normalizado = pd.DataFrame(scaler_minmax.fit_transform(df[variaveis]),
                              columns=[f"{col}_norm" for col in variaveis],
                              index=df.index)

# Padronização (Z-score: média 0 e desvio padrão 1)
scaler_standard = StandardScaler()
df_padronizado = pd.DataFrame(scaler_standard.fit_transform(df[variaveis]),
                              columns=[f"{col}_padrao" for col in variaveis],
                              index=df.index)

# 4. Reamostragem mensal da potência média
potencia_mensal = df['potencia_W'].resample('ME').mean()

# ==============================================================================
# GRÁFICO 1: Dados Originais (Escalas totalmente diferentes)
# ==============================================================================
plt.figure(figsize=(10, 5))
sns.boxplot(data=df[variaveis], palette='Set2')
plt.title('Distribuição Original dos Dados\n(Repare como a Potência esmaga as outras variáveis)\n', fontsize=14)
plt.ylabel('Valores Originais')
plt.show()
print()

# ==============================================================================
# GRÁFICO 2: Dados Normalizados (Min-Max)
# ==============================================================================
plt.figure(figsize=(10, 5))
sns.boxplot(data=df_normalizado, palette='Set2')
plt.title('Dados Normalizados (Min-Max)\n(entre 0 e 1)\n', fontsize=14)
plt.ylabel('Escala (0 a 1)')
plt.show()
print()

# ==============================================================================
# GRÁFICO 3: Dados Padronizados (Z-Score)
# ==============================================================================
plt.figure(figsize=(10, 5))
sns.boxplot(data=df_padronizado, palette='Set2')
plt.title('Dados Padronizados (Z-Score)\n(Média centralizada no 0 e desvio padrão 1)\n', fontsize=14)
plt.ylabel('Desvios Padrão')
plt.show()

"""# GRÁFICOS"""

# ==============================================================================
# GRÁFICOS
# ==============================================================================

plt.figure(figsize=(18, 12))

# Gráfico 4: Linha - Variação da Tensão ao longo do tempo
plt.subplot(3, 1, 1)
plt.plot(df.index, df['tensao_V'], color='orange', linewidth=1)
plt.title('Variação da Tensão (V) ao longo do tempo', fontsize=14)
plt.xlabel('Data')
plt.ylabel('Tensão (V)')
plt.xticks(rotation=45)


# Gráfico 5: Dispersão - Corrente vs Potência
plt.subplot(3, 1, 2)
sns.scatterplot(x=df['corrente_A'], y=df['potencia_W'], color='blue', alpha=0.6)
plt.title('Dispersão: Corrente (A) x Potência (W)', fontsize=14)
plt.xlabel('Corrente (A)')
plt.ylabel('Potência (W)')


# Gráfico 6: Barras - Média Mensal da Potência
plt.subplot(3, 1, 3)
potencia_mensal.plot(kind='bar', color='teal')
meses_formatados = [data.strftime('%Y-%m') for data in potencia_mensal.index]
plt.xticks(ticks=range(len(meses_formatados)), labels=meses_formatados, rotation=45)
plt.title('Média Mensal da Potência (W)', fontsize=14)
plt.xlabel('Mês')
plt.ylabel('Potência Média (W)')

plt.tight_layout()
plt.show()

"""# MODELO DE REGRESSÃO LINEAR"""

# 1. Dividir os dados em conjuntos de treino (80%) e teste (20%)
X = df[['corrente_A']] # Variável Independente
y = df['potencia_W']   # Variável Dependente (Alvo)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Implementar o modelo de regressão linear utilizando Scikit Learn
modelo_lr = LinearRegression()
modelo_lr.fit(X_train, y_train)

# Fazendo predições com a base de teste
y_pred = modelo_lr.predict(X_test)

# 3. Analisar os coeficientes gerados pelo modelo
inclinacao = modelo_lr.coef_[0]
intercepto = modelo_lr.intercept_

# 4. Avaliar o desempenho do modelo (RMSE e R²)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

# ==============================================================================
# CONTAGEM E VERIFICAÇÃO DE SEGURANÇA
# ==============================================================================

# 1. Calculando os totais
total_linhas = len(df)
linhas_treino = len(X_train)
linhas_teste = len(X_test)

# 2. Exibindo a divisão (80/20)
print(f"Total de dados originais: {total_linhas} linhas")
print("---")
print(f"Dados de Treino: {linhas_treino} linhas ({(linhas_treino/total_linhas)*100:.1f}%)")
print(f"Dados de Teste: {linhas_teste} linhas ({(linhas_teste/total_linhas)*100:.1f}%)\n")

# 3. Verificação de segurança (Garante que X e Y têm o mesmo tamanho)
print("Verificação de segurança:")
print(f"X_train e y_train têm o mesmo tamanho? {len(X_train) == len(y_train)}")
print(f"X_test e y_test têm o mesmo tamanho? {len(X_test) == len(y_test)}")

print("-" * 40)
print("RESULTADOS DA REGRESSÃO LINEAR")
print("-" * 40)
print(f"Equação: Potência = {inclinacao:.2f} * Corrente + ({intercepto:.2f})")
print(f"Inclinação (Coeficiente Angular): {inclinacao:.2f}")
print(f"Intercepto (Coeficiente Linear):  {intercepto:.2f}")
print(f"RMSE (Raiz do Erro Quadrático Médio): {rmse:.2f} W")
print(f"R² (Coeficiente de Determinação):     {r2 * 100:.2f}%")
print("-" * 112)

# 5. Comparar graficamente os valores previstos com os valores reais
plt.figure(figsize=(10, 6))
plt.scatter(X_test, y_test, color='blue', alpha=0.5, label='Valores Reais (Teste)')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Valores Previstos (Reta de Regressão)')
plt.title('Regressão Linear: Valores Reais vs Valores Previstos', fontsize=14)
plt.xlabel('Corrente (A)')
plt.ylabel('Potência (W)')
plt.legend()
plt.show()